version: "3.7"
services:
  python-inmobly:
    container_name: python-inmobly
    hostname: python-inmobly
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo-inmobly
    ports:
      - ${APP_PORT}:5000
    volumes:
      - ./:/usr/src/app
    command: python run.py

  mongo-inmobly:
    image: mongo
    container_name: mongo-inmobly
    hostname: mongo-inmobly
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
